const FETCH_DATA = 'hw4/items/FETCH_DATA';
const SET_IS_LOADING = 'hw4/items/SET_IS_LOADING';
const SET_MODAL_ID = 'hw4/items/SET_MODAL_ID';
const FETCH_FAVORITES = 'hw4/items/FETCH_FAVORITES';
const TOGGLE_FAVORITES ='hw4/items/TOGGLE_FAVORITES';
const FETCH_CARD = 'hw4/items/FETCH_CARD';
const ADD_TO_CARD = 'hw4/items/ADD_TO_CARD';
const SET_ITEM = 'hw4/items/SET_ITEM';
const DELETE_ITEM = 'hw4/items/DELETE_ITEM';
const CLEAR_CARD = 'hw4/items/CLEAR_CARD';


export default {FETCH_DATA , SET_IS_LOADING, SET_MODAL_ID , FETCH_FAVORITES, TOGGLE_FAVORITES, ADD_TO_CARD, FETCH_CARD , SET_ITEM, DELETE_ITEM, CLEAR_CARD};